### Cerate a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "Marco@bla.com",
    "password": "testpwd"
}

### sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "Marco@bla.com",
    "password": "testpwd"
}

### Get user by id
GET http://localhost:3000/auth/1

### Find all users with email 
GET http://localhost:3000/auth/?email=test@bla.co

### delete user by id
DELETE  http://localhost:3000/auth/2

### update user
PATCH http://localhost:3000/auth/3
content-Type: application/json

{
    "email": "ךובקט@bla.com"
}

